use KASETY_504_09

CREATE TABLE OSOBY(
    ID int PRIMARY key IDENTITY(1,1),
    NAZWISKO    CHAR(30) not null,
    IMIE    CHAR(15) not null,
    ADRES CHAR(30)  null DEFAULT('BRAK DANYCH'),
    STAN_CYWILNY CHAR(30) null,
    TELEFON_DOM CHAR(15)  null,
    TELEFON_PRACA CHAR(15)  null,
    ZAROBKI DECIMAL(8,2) CHECK (ZAROBKI BETWEEN 100 AND 20000),
    PLEC_OSOBY CHAR(1) NOT NULL,
    KOLOR_OCZU CHAR(1) NOT NULL CHECK (KOLOR_OCZU IN ('Z', 'K', 'C')) DEFAULT ('Z')

)
GO

PRINT '****tworzenie reguly (roule) plec_xyz'
GO
create RULE PLEC_XYZ AS @X IN ('M','K')
GO

PRINT 'DOWIAZANIE KOLUMNY KLIENCI PLEC DO REGULY PLEC_XYZ'
EXEC sp_bindrule PLEC_XYZ, 'OSOBY.PLEC_OSOBY'
GO

CREATE DEFAULT BRAK_INF AS 'BRAK INFORMACJI'
GO

--DOWIAZANIE KOLUMNY OSOBY.STAN CYWULNY NMIENNIEJ DOMYSLNEJ BRAK INFO
EXEC sp_bindefault BRAK_INF, 'OSOBY.STAN_CYWILNY'
GO








INSERT INTO OSOBY VALUES ('KOWAL', 'JAN', NULL , NULL ,NULL ,null , 200 , 'm','K')
INSERT INTO OSOBY VALUES ('ROBOT', 'ANNA', DEFAULT,DEFAULT,'(22)431143', null,1000,'k',DEFAULT)


USE KASETY_504_09

CREATE TABLE OSOBY_1(
    ID int PRIMARY key IDENTITY(1,1),
    NAZWISKO    CHAR(30) not null,
    IMIE    CHAR(15) not null,
    ADRES CHAR(30)  null DEFAULT('BRAK DANYCH'),
    STAN_CYWILNY CHAR(30) null,
    TELEFON_DOM CHAR(15)  null,
    TELEFON_PRACA CHAR(15)  null,
    ZAROBKI DECIMAL(8,2) CHECK (ZAROBKI BETWEEN 100 AND 20000),
    PLEC_OSOBY CHAR(1) NOT NULL,
    KOLOR_OCZU CHAR(1) NOT NULL CHECK (KOLOR_OCZU IN ('Z', 'K', 'C')) DEFAULT ('Z')

)
GO

INSERT INTO OSOBY_1 VALUES ('KOWAL', 'JAN', NULL , NULL ,NULL ,null , 200 , 'm','K')
INSERT INTO OSOBY_1 VALUES ('ROBOT', 'ANNA', DEFAULT,DEFAULT,'(22)431143', null,1000,'k',DEFAULT)




---- INSERT into OSOBY (ID, NAZWISKO, IMIE)

SELECT * FROM OSOBY_1

DELETE FROM OSOBY
TRUNCATE TABLE OSOBY


